import os
os.makedirs("\\body")
os.makedirs("\\head")
os.makedirs("\\play")
os.makedirs("\\swim")
os.makedirs("\\think")
os.makedirs("\\wrong")
file1=open("\\body\\hand.txt","w")
file1.close()
file1=open("\\play\\sing.bas","w")
file1.close()
file1=open("\\think\\think.new","w")
file1.close()
file1=open("\\wrong\\box.exe","wb")
file1.close()